rcsoccersim/manual

source/soccerclient.rst

[Team Jyo_sen from Japan]  Update soccerclient.rst. We migrated section 6  from the old manual.

[Team Jyo_sen from Japan] Update soccerclient.rst

---

source/coach.rst

Updated the coach.rst till the section 7.7.4.

[Team RoboCIn from Brazil] Update coach.rst

---

source/soccerserver.rst

Updated the stamina model in section 4.5.2.
Added the explanation about the stamina capacity.

[Team HELIOS2020 from Japan] Update soccerserver.rst

---

source/soccerserver.rst

We pull the request again, based on your comments.

[Team MT2020 from China ] Update soccerserver.rst

---

source/soccerserver.rst

Updated the tackle model in section 4.5.6. Added the explanation about the tackle probability.

[Team YuShan2020 from China ] Update soccerserver.rst

---

source/soccerserver.rst

Added new sub-section on sideward and omni-directional dashes

[Team FRA-UNIted from Germany] Update soccerserver.rst

---

docs/soccerserver.html
source/soccerserver.rst

Ri-one
We have added parameters that we did not write in the old documentation. The text was also slightly modified.

Wrote Heterogeneous

---

source/soccerserver.rst

The Soccerserver Parameters section migrated from original document.

 [Team KN2C from Iran] Update soccerserver.rst

---

source/coach.rst

We updated after the section 7.7.5.

[Team ITAndroids from Brazil] Update coach.rst

---

source/soccerserver.rst

Added more info in section 4.5.1. Catch Model, about  heterogenous parameters

[Team Oxsy from Romania] Update soccerserver.rst

---

source/soccerserver.rst

Add Referee Model
Add Play Modes and referee messages
Add The Soccer Simulation
Add Description of the simulation algorithm

[Team HillStone from Japan] Update soccerserver.rst

---

source/soccerserver.rst

[Team Razi From Iran] update soccerserver.rst

---

source/gettingstarted.rst
source/references.rst
source/soccermonitor.rst

gettingstarted.rst - section 3.7
references.rst - section 5.5
soccermonitor.rst - section 8.3 ~ 8.8
Co-authored-by: Gabriel Cosme Barbosa <gabriel.cosme@thunderatz.org>

[Team ThunderLeague from Brazil] Update sections 3.7, 5.5, 8.3~8.8

---

source/soccerserver.rst

[Team Persepolis from Iran]Additional information about game modes

[Team Persepolis from Iran]Update soccerserver.rst

---

source/soccermonitor.rst

[Team YuShan2022 from China]Update soccermonitor.rst

---

source/introduction.rst

Started with the addition of sub-sections to the part on "History of the RoboCup Simulation League". This update / pull request is part of the qualification material of team FRA-UNIted for RoboCup 2022.

[Team FRA-UNIted from Germany] Update introduction.rst

---

source/coach.rst
source/soccerclient.rst
source/soccerserver.rst

This pull request is part of the qualification material of team RobôCIn for RoboCup 2022.

[Team RobôCIn from Brazil] Update the sections 4.9, 6.1, 7.4.3 and 7.7.1

---

source/soccerserver.rst

Add content to subsection 4.4.4 (Collision with goal posts) to close #78.
Please, feel free to request changes or any other important requests.

[Team ThunderLeague from Brasil] Update section 4.4.4

---

source/soccerserver.rst

* Added improvement of the catch model in section 4.6.1

[Team Oxsy from Romania] Update section 4.6.1

---

source/soccerserver.rst

[Team Persepolis from Iran]

---

source/coach.rst

Small improvement to the coach doc

Minor fixes to coach.rst
